SPII-32: Joystick controller
rekise/vrx pull request #4
Opened 2023-07-04 23:01 UTC by aniket11bh

2023-07-06 01:42 UTC, sumandeepb requested changes
Add to .gitignore:

.vscode/

If there are specific debug and/or editor settings that needs to be standardized, we can do that seperately using specifig settings files.

2023-07-06 01:42 UTC, sumandeepb commented on .vscode/c_cpp_properties.json
this has local settings, should not be checked in.

2023-07-06 01:42 UTC, sumandeepb commented on .vscode/settings.json
this has local settings, should not be checked in.

2023-07-07 06:58 UTC, aniket11bh commented
@sumandeepb can you approve this?

2023-07-08 07:43 UTC, sumandeepb approved these changes

2023-07-08 07:43 UTC, merged